[project]
name = "threetl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tranduc2204", email = "trandc3015@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
threetl = "threetl:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
